__version__ = '2.1'
__author__ = 'Frederic Laurencin'
__title__ = 'ciscomation'
__author_email__ = 'flaurencin@free.fr'
__license__ = 'http://www.apache.org/licenses/LICENSE-2.0'
__copyright__ = 'Copyright 2016 Frederic Laurencin'
